export const INITIAL_ITEMS = Object.freeze([
  {
    id: "x-agent-memory",
    source: "x_list",
    sourceLabel: "X List",
    title: "智能体开始拥有跨任务的长期记忆",
    summary: "新的记忆层把事实、偏好与任务上下文分开存储，重点不是记得更多，而是知道何时遗忘。",
    meta: "12 分钟前",
    tag: "Agent",
    metric: "2.8k 浏览",
    image: { src: "/media/memory.svg", width: 720, height: 405, alt: "记忆节点关系示意" },
  },
  {
    id: "github-terminal-agents",
    source: "github",
    sourceLabel: "GitHub",
    title: "terminal-agents：在终端里协调多个编码代理",
    summary: "提供任务隔离、执行日志和可恢复检查点，今天新增了浏览器测试适配器。",
    meta: "趋势榜 #1",
    tag: "开源工具",
    metric: "18.4k stars",
  },
  {
    id: "news-model-context",
    source: "news",
    sourceLabel: "官方新闻",
    title: "模型上下文不再等于一条无限增长的聊天记录",
    summary: "研究团队公开分层上下文方案：短期工作区、可验证记忆和按需检索共同控制推理成本。",
    meta: "28 分钟前 · 5 分钟阅读",
    tag: "研究",
    metric: "官方博客",
    image: { src: "/media/context.svg", width: 720, height: 480, alt: "分层上下文结构示意" },
  },
  {
    id: "ph-canvas-code",
    source: "product_hunt",
    sourceLabel: "Product Hunt",
    title: "Canvas Code",
    summary: "把网页草图直接转成可编辑组件，保留设计 token、响应式约束与交互状态。",
    meta: "今日产品 #2",
    tag: "设计工程",
    metric: "642 upvotes",
    image: { src: "/media/canvas.svg", width: 720, height: 405, alt: "界面组件画布示意" },
  },
  {
    id: "paper-efficient-video",
    source: "hf_paper",
    sourceLabel: "AI 论文",
    title: "更少视觉 token，也能理解长视频",
    summary: "论文用事件密度选择关键片段，在长视频问答基准上减少约六成视觉计算。",
    meta: "HF Daily Paper",
    tag: "多模态",
    metric: "184 赞",
  },
  {
    id: "event-agent-night",
    source: "event",
    sourceLabel: "AI 活动",
    title: "Agent Builder Night · 上海",
    summary: "四个团队现场拆解从原型到生产的代理工作流，包含可靠性、观测和成本控制。",
    meta: "周六 19:30 · 徐汇",
    tag: "线下",
    metric: "余 23 席",
    image: { src: "/media/event.svg", width: 720, height: 360, alt: "夜间开发者活动海报示意" },
  },
  {
    id: "x-small-models",
    source: "x_list",
    sourceLabel: "X List",
    title: "小模型的优势正在从成本转向可控性",
    summary: "当工具调用链变长，低延迟、稳定格式和可本地部署本身就成为产品能力。",
    meta: "46 分钟前",
    tag: "观点",
    metric: "936 浏览",
  },
  {
    id: "github-eval-recipes",
    source: "github",
    sourceLabel: "GitHub",
    title: "eval-recipes：面向真实产品路径的评测配方",
    summary: "不只测回答正确率，还覆盖工具失败、恢复路径、延迟预算和多轮状态漂移。",
    meta: "趋势榜 #4",
    tag: "评测",
    metric: "7.2k stars",
    image: { src: "/media/eval.svg", width: 720, height: 500, alt: "评测流程卡片示意" },
  },
  {
    id: "news-robotics-data",
    source: "news",
    sourceLabel: "官方新闻",
    title: "机器人数据集开始记录失败后的恢复动作",
    summary: "新版数据不再只保留成功轨迹，而是把犹豫、碰撞和二次规划作为训练信号。",
    meta: "1 小时前 · 7 分钟阅读",
    tag: "机器人",
    metric: "实验室博客",
  },
]);

export const SOURCE_ORDER = Object.freeze([
  "X List",
  "GitHub",
  "官方新闻",
  "Product Hunt",
  "AI 论文",
  "AI 活动",
]);

export const MEDIA_PALETTES = Object.freeze({
  memory: ["#161616", "#d8d8d8", "MEMORY / SIGNAL"],
  context: ["#ece8df", "#2b2b2b", "CONTEXT LAYERS"],
  canvas: ["#dfe8e6", "#143b37", "CANVAS / CODE"],
  event: ["#181818", "#ff8a00", "BUILDER NIGHT"],
  eval: ["#e5e5e5", "#242424", "EVAL / RECIPES"],
});
